### PR TITLE
Added Switzerland Calendar

### PR DESCRIPTION
**Pull request by olivsoft**
Dear martinjw

I have added a calendar for Switzerland (with German holiday names). Feel free to take it up into your main branch! 
I have tried to be consistent with your coding style, tests have gone through without problems.

Sincerely, Oliver (olivsoft)

### CODE REVIEW

**Comment by martinjw** [comment]
Thanks! Good work!

**Comment by tossnet** [comment]
There is a little problem with theses dates. It's quite difficult with the different regions : Currently the code return this :

**Comment by martinjw** [comment]
We use enums for other countries (if possible with the ISO 3166-2 codes).

Eg Germany https://github.com/martinjw/Holiday/blob/master/src/PublicHoliday/GermanPublicHoliday.cs

Also UK https://github.com/martinjw/Holiday/blob/master/src/PublicHoliday/UKBankHoliday.cs
Canada and Australia also have states/provinces.

The state can be set as a property, and/or an overloaded constructor (always supply a default constructor, which will supply federal holidays or a superset of holidays). Eg
```c#
//constructor overload
IList<DateTime> result = new CanadaPublicHoliday("SK").PublicHolidays(2016);
//directly set a property
var calendar = new GermanPublicHoliday { State = GermanPublicHoliday.States.SN };
```

**Comment by tossnet** [comment]
I worked on the Swiss holidays and found a lot of problems :(  I'll let you look at what I've done: [https://github.com/tossnet/Holiday/blob/master/src/PublicHoliday/SwitzerlandPublicHoliday.cs](https://github.com/tossnet/Holiday/blob/master/src/PublicHoliday/SwitzerlandPublicHoliday.cs)

**Pull request merged**
