### PR TITLE
Added support to observe Anzac day (NZ) and boxing day issue.

### PR DESCRIPTION
**Pull request by shanerogers**
Fixed bug when both xmas and boxing day land on the weekend.
Added support to observe Anzac day.

### CODE REVIEW

**Comment by shanerogers** [comment]
@martinjw is it possible to have this looked at soon? 
We have a pending release for a big company that requires these fixes. :)

**Comment by martinjw** [comment]
Thanks, will release to nuget in a day or so...

**Comment by shanerogers** [comment]
Thank you very much

**Comment by martinjw** [comment]
Now on nuget

**Comment by shanerogers** [comment]
Thank you. Will use it this morning ;)

**Pull request merged**
